# 1. arange() - create a data with pattern 
# syntax : arange(start , stop , step)
# start : default = 0 ,stop = need to mention , step : default = 1

In [1]:
import numpy as np

In [ ]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
np.arange(2,dtype=bool)

array([False,  True])

# zeros - create a data with 0
# syntax : np.zeros(shape)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [16]:
np.zeros(2,dtype=bool)

array([False, False])

In [21]:
np.zeros([2,4,4],dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [22]:
np.zeros([2,4,4],dtype=str)

array([[['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']],

       [['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']]], dtype='<U1')

# ones : create a data with 1 
# syntax : np.ones (shape) 

In [23]:
np.ones([2,4,4],dtype=int)  

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

# eye =  create a data with identity matrix
# syntax : np.eye(n)


In [30]:
np.eye(3 ,4 ,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

# linspace : equally distributes  the data 
# syntax : np.linspace(start , stop , numberofvalues)

In [34]:
np.linspace(1,100,2,endpoint=False)

array([ 1. , 50.5])

## Reshape 
# syntax :np.reshape(shape) 

In [37]:
a = np.arange(1,11)

In [38]:
np.reshape(a,(2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Broadcasting
# it helps to do mathematical operations on data without using loops 

In [43]:
a = np.arange(1,6)

In [44]:
a*3

array([ 3,  6,  9, 12, 15])

In [45]:
a = a*3

In [46]:
a + 100

array([103, 106, 109, 112, 115])